spring:
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  ###mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tabPat?serverTimezone=Asia/Shanghai
    username: root
    password: root
  ###Redis
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      timeout: 2000ms
      password: 123456 #密码
      jedis:
        pool:
          max-active: 10
          max-idle: 8
          min-idle: 2
          max-wait: 1000ms
logging:
  config: classpath:config/log4j2.yml

#mybaits
mybatis-plus:
  # xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
  mapper-locations: classpath:mapper/*.xml
  # 以下配置均有默认值,可以不设置
  global-config:
    db-config:
      #主键类型 AUTO:"数据库ID自增" INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: auto
      #字段策略 IGNORED:"忽略判断"  NOT_NULL:"非 NULL 判断")  NOT_EMPTY:"非空判断"
      field-strategy: NOT_EMPTY
      #数据库类型
      db-type: MYSQL
  configuration:
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
    # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    call-setters-on-nulls: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

### jwt
jwt:
  ###过期时间 单位s
  time: 2592000
  ###安全密钥
  secret: "7b718b39880f3e47f291509bdca6447a2691aa7fab6bc664e28c7e8588e795d6094a1e95ecbf0b728bd062dcc5bc5d2321a784b12acac17f479df62723550bf8"
  ###token前缀
  prefix: "Bearer "
  ###http头key
  header: "Authorization"

# 分页配置
pagehelper:
  helper-dialect: mysql	#使用的数据库. mysql, oracle, sqlite
  reasonable: true #开启优化,在分页页码结果没有数据的时候,会显示有数据的页码数据,也就是当当前页<1时,返回第 1 页, 当当前页 > 最大页时, 返回最后一页的数据.
  support-methods-arguments: true #是否支持接口参数来传递分页参数，默认false
  pageSizeZero: false #表示当 pageSize=0 时返回所有
  params: count=countSql


